// CodeMADD/src/main/webapp/app/entities/checkin/detail/checkin-detail.component.ts
import { Component, Input } from '@angular/core';
import { ActivatedRoute, RouterModule } from '@angular/router';

import SharedModule from 'app/shared/shared.module';
import { DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe } from 'app/shared/date';
import { ICheckin } from '../checkin.model';

@Component({
  standalone: true,
  selector: 'jhi-checkin-detail',
  templateUrl: './checkin-detail.component.html',
  imports: [SharedModule, RouterModule, DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe],
})
export class CheckinDetailComponent {
  @Input() checkin: ICheckin | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <div *ngIf="checkin">
      <h2 data-cy="checkinDetailsHeading">
        <span jhiTranslate="codeMaddApp.checkin.detail.title">__jhiTransformTranslate__('codeMaddApp.checkin.detail.title')</span>
      </h2>

      <hr />

      <jhi-alert-error></jhi-alert-error>

      <jhi-alert></jhi-alert>

      <dl class="row-md jh-entity-details">
        <dt><span jhiTranslate="global.field.id">__jhiTransformTranslate__('global.field.id')</span></dt>
        <dd>
          <span>{{ checkin.id }}</span>
        </dd>
        <dt><span jhiTranslate="codeMaddApp.checkin.checkinTime">__jhiTransformTranslate__('codeMaddApp.checkin.checkinTime')</span></dt>
        <dd>
          <span>{{ checkin.checkinTime | formatMediumDatetime }}</span>
        </dd>
        <dt><span jhiTranslate="codeMaddApp.checkin.checkoutTime">__jhiTransformTranslate__('codeMaddApp.checkin.checkoutTime')</span></dt>
        <dd>
          <span>{{ checkin.checkoutTime | formatMediumDatetime }}</span>
        </dd>
        <dt><span jhiTranslate="codeMaddApp.checkin.faceVerified">__jhiTransformTranslate__('codeMaddApp.checkin.faceVerified')</span></dt>
        <dd>
          <span>{{ checkin.faceVerified }}</span>
        </dd>
        <dt><span jhiTranslate="codeMaddApp.checkin.trip">__jhiTransformTranslate__('codeMaddApp.checkin.trip')</span></dt>
        <dd>
          <div *ngIf="checkin.trip">
            <a [routerLink]="['/trip', checkin.trip.id, 'view']">{{ checkin.trip.id }}</a>
          </div>
        </dd>
      </dl>

      <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
        <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back"
          >__jhiTransformTranslate__('entity.action.back')</span
        >
      </button>

      <button type="button" [routerLink]="['/checkin', checkin.id, 'edit']" class="btn btn-primary">
        <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit"
          >__jhiTransformTranslate__('entity.action.edit')</span
        >
      </button>
    </div>
  </div>
</div>

// src/main/webapp/app/entities/checkin/checkin-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './checkin.reducer';

export const CheckinDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const checkinEntity = useAppSelector(state => state.checkin.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="checkinDetailsHeading">
          <Translate contentKey="backendHeThongNhungApp.checkin.detail.title">Checkin</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{checkinEntity.id}</dd>
          <dt>
            <span id="checkinTime">
              <Translate contentKey="backendHeThongNhungApp.checkin.checkinTime">Checkin Time</Translate>
            </span>
          </dt>
          <dd>
            {checkinEntity.checkinTime ? <TextFormat value={checkinEntity.checkinTime} type="date" format={APP_DATE_FORMAT} /> : null}
          </dd>
          <dt>
            <span id="checkoutTime">
              <Translate contentKey="backendHeThongNhungApp.checkin.checkoutTime">Checkout Time</Translate>
            </span>
          </dt>
          <dd>
            {checkinEntity.checkoutTime ? <TextFormat value={checkinEntity.checkoutTime} type="date" format={APP_DATE_FORMAT} /> : null}
          </dd>
          <dt>
            <span id="faceVerified">
              <Translate contentKey="backendHeThongNhungApp.checkin.faceVerified">Face Verified</Translate>
            </span>
          </dt>
          <dd>{checkinEntity.faceVerified ? 'true' : 'false'}</dd>
          <dt>
            <Translate contentKey="backendHeThongNhungApp.checkin.trip">Trip</Translate>
          </dt>
          <dd>{checkinEntity.trip ? checkinEntity.trip.id : ''}</dd>
        </dl>
        <Button tag={Link} to="/checkin" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/checkin/${checkinEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default CheckinDetail;
