// CodeHTN/src/main/webapp/app/entities/checkin/update/checkin-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize, map } from 'rxjs/operators';

import SharedModule from 'app/shared/shared.module';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';

import { ITrip } from 'app/entities/trip/trip.model';
import { TripService } from 'app/entities/trip/service/trip.service';
import { ICheckin } from '../checkin.model';
import { CheckinService } from '../service/checkin.service';
import { CheckinFormService, CheckinFormGroup } from './checkin-form.service';

@Component({
  standalone: true,
  selector: 'jhi-checkin-update',
  templateUrl: './checkin-update.component.html',
  imports: [SharedModule, FormsModule, ReactiveFormsModule],
})
export class CheckinUpdateComponent implements OnInit {
  isSaving = false;
  checkin: ICheckin | null = null;

  tripsSharedCollection: ITrip[] = [];

  editForm: CheckinFormGroup = this.checkinFormService.createCheckinFormGroup();

  constructor(
    protected checkinService: CheckinService,
    protected checkinFormService: CheckinFormService,
    protected tripService: TripService,
    protected activatedRoute: ActivatedRoute,
  ) {}

  compareTrip = (o1: ITrip | null, o2: ITrip | null): boolean => this.tripService.compareTrip(o1, o2);

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ checkin }) => {
      this.checkin = checkin;
      if (checkin) {
        this.updateForm(checkin);
      }

      this.loadRelationshipsOptions();
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const checkin = this.checkinFormService.getCheckin(this.editForm);
    if (checkin.id !== null) {
      this.subscribeToSaveResponse(this.checkinService.update(checkin));
    } else {
      this.subscribeToSaveResponse(this.checkinService.create(checkin));
    }
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<ICheckin>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe({
      next: () => this.onSaveSuccess(),
      error: () => this.onSaveError(),
    });
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(checkin: ICheckin): void {
    this.checkin = checkin;
    this.checkinFormService.resetForm(this.editForm, checkin);

    this.tripsSharedCollection = this.tripService.addTripToCollectionIfMissing<ITrip>(this.tripsSharedCollection, checkin.trip);
  }

  protected loadRelationshipsOptions(): void {
    this.tripService
      .query()
      .pipe(map((res: HttpResponse<ITrip[]>) => res.body ?? []))
      .pipe(map((trips: ITrip[]) => this.tripService.addTripToCollectionIfMissing<ITrip>(trips, this.checkin?.trip)))
      .subscribe((trips: ITrip[]) => (this.tripsSharedCollection = trips));
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2 id="jhi-checkin-heading" data-cy="CheckinCreateUpdateHeading" jhiTranslate="codeHtnApp.checkin.home.createOrEditLabel">
        __jhiTransformTranslate__('codeHtnApp.checkin.home.createOrEditLabel')
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="mb-3" *ngIf="editForm.controls.id.value !== null">
          <label class="form-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="mb-3">
          <label class="form-label" jhiTranslate="codeHtnApp.checkin.checkinTime" for="field_checkinTime">Checkin Time</label>
          <div class="d-flex">
            <input
              id="field_checkinTime"
              data-cy="checkinTime"
              type="datetime-local"
              class="form-control"
              name="checkinTime"
              formControlName="checkinTime"
              placeholder="YYYY-MM-DD HH:mm"
            />
          </div>
        </div>

        <div class="mb-3">
          <label class="form-label" jhiTranslate="codeHtnApp.checkin.checkoutTime" for="field_checkoutTime">Checkout Time</label>
          <div class="d-flex">
            <input
              id="field_checkoutTime"
              data-cy="checkoutTime"
              type="datetime-local"
              class="form-control"
              name="checkoutTime"
              formControlName="checkoutTime"
              placeholder="YYYY-MM-DD HH:mm"
            />
          </div>
        </div>

        <div class="mb-3">
          <label class="form-label" jhiTranslate="codeHtnApp.checkin.faceVerified" for="field_faceVerified">Face Verified</label>
          <input
            type="checkbox"
            class="form-check"
            name="faceVerified"
            id="field_faceVerified"
            data-cy="faceVerified"
            formControlName="faceVerified"
          />
        </div>

        <div class="mb-3">
          <label class="form-label" jhiTranslate="codeHtnApp.checkin.trip" for="field_trip"
            >__jhiTransformTranslate__('codeHtnApp.checkin.trip')</label
          >
          <select class="form-control" id="field_trip" data-cy="trip" name="trip" formControlName="trip" [compareWith]="compareTrip">
            <option [ngValue]="null"></option>
            <option [ngValue]="tripOption" *ngFor="let tripOption of tripsSharedCollection">{{ tripOption.id }}</option>
          </select>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" data-cy="entityCreateCancelButton" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel"
            >__jhiTransformTranslate__('entity.action.cancel')</span
          >
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save"
            >__jhiTransformTranslate__('entity.action.save')</span
          >
        </button>
      </div>
    </form>
  </div>
</div>

// src/main/webapp/app/entities/checkin/checkin-update.tsx
import React, { useState, useEffect } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Button, Row, Col, FormText } from 'reactstrap';
import { isNumber, Translate, translate, ValidatedField, ValidatedForm } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { ITrip } from 'app/shared/model/trip.model';
import { getEntities as getTrips } from 'app/entities/trip/trip.reducer';
import { ICheckin } from 'app/shared/model/checkin.model';
import { getEntity, updateEntity, createEntity, reset } from './checkin.reducer';

export const CheckinUpdate = () => {
  const dispatch = useAppDispatch();

  const navigate = useNavigate();

  const { id } = useParams<'id'>();
  const isNew = id === undefined;

  const trips = useAppSelector(state => state.trip.entities);
  const checkinEntity = useAppSelector(state => state.checkin.entity);
  const loading = useAppSelector(state => state.checkin.loading);
  const updating = useAppSelector(state => state.checkin.updating);
  const updateSuccess = useAppSelector(state => state.checkin.updateSuccess);

  const handleClose = () => {
    navigate('/checkin' + location.search);
  };

  useEffect(() => {
    if (isNew) {
      dispatch(reset());
    } else {
      dispatch(getEntity(id));
    }

    dispatch(getTrips({}));
  }, []);

  useEffect(() => {
    if (updateSuccess) {
      handleClose();
    }
  }, [updateSuccess]);

  const saveEntity = values => {
    values.checkinTime = convertDateTimeToServer(values.checkinTime);
    values.checkoutTime = convertDateTimeToServer(values.checkoutTime);

    const entity = {
      ...checkinEntity,
      ...values,
      trip: trips.find(it => it.id.toString() === values.trip.toString()),
    };

    if (isNew) {
      dispatch(createEntity(entity));
    } else {
      dispatch(updateEntity(entity));
    }
  };

  const defaultValues = () =>
    isNew
      ? {
          checkinTime: displayDefaultDateTime(),
          checkoutTime: displayDefaultDateTime(),
        }
      : {
          ...checkinEntity,
          checkinTime: convertDateTimeFromServer(checkinEntity.checkinTime),
          checkoutTime: convertDateTimeFromServer(checkinEntity.checkoutTime),
          trip: checkinEntity?.trip?.id,
        };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="backendHeThongNhungApp.checkin.home.createOrEditLabel" data-cy="CheckinCreateUpdateHeading">
            <Translate contentKey="backendHeThongNhungApp.checkin.home.createOrEditLabel">Create or edit a Checkin</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <ValidatedForm defaultValues={defaultValues()} onSubmit={saveEntity}>
              {!isNew ? (
                <ValidatedField
                  name="id"
                  required
                  readOnly
                  id="checkin-id"
                  label={translate('global.field.id')}
                  validate={{ required: true }}
                />
              ) : null}
              <ValidatedField
                label="Checkin Time"
                id="checkin-checkinTime"
                name="checkinTime"
                data-cy="checkinTime"
                type="datetime-local"
                placeholder="YYYY-MM-DD HH:mm"
              />
              <ValidatedField
                label="Checkout Time"
                id="checkin-checkoutTime"
                name="checkoutTime"
                data-cy="checkoutTime"
                type="datetime-local"
                placeholder="YYYY-MM-DD HH:mm"
              />
              <ValidatedField
                label="Face Verified"
                id="checkin-faceVerified"
                name="faceVerified"
                data-cy="faceVerified"
                check
                type="checkbox"
              />
              <ValidatedField id="checkin-trip" name="trip" data-cy="trip" label="Trip" type="select">
                <option value="" key="0" />
                {trips
                  ? trips.map(otherEntity => (
                      <option value={otherEntity.id} key={otherEntity.id}>
                        {otherEntity.id}
                      </option>
                    ))
                  : null}
              </ValidatedField>
              <Button tag={Link} id="cancel-save" data-cy="entityCreateCancelButton" to="/checkin" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </ValidatedForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

export default CheckinUpdate;
