// src/main/webapp/app/entities/trip/trip-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './trip.reducer';

export const TripDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const tripEntity = useAppSelector(state => state.trip.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="tripDetailsHeading">
          <Translate contentKey="backendHeThongNhungApp.trip.detail.title">Trip</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{tripEntity.id}</dd>
          <dt>
            <span id="startTime">
              <Translate contentKey="backendHeThongNhungApp.trip.startTime">Start Time</Translate>
            </span>
          </dt>
          <dd>{tripEntity.startTime ? <TextFormat value={tripEntity.startTime} type="date" format={APP_DATE_FORMAT} /> : null}</dd>
          <dt>
            <span id="endTime">
              <Translate contentKey="backendHeThongNhungApp.trip.endTime">End Time</Translate>
            </span>
          </dt>
          <dd>{tripEntity.endTime ? <TextFormat value={tripEntity.endTime} type="date" format={APP_DATE_FORMAT} /> : null}</dd>
          <dt>
            <span id="status">
              <Translate contentKey="backendHeThongNhungApp.trip.status">Status</Translate>
            </span>
          </dt>
          <dd>{tripEntity.status}</dd>
          <dt>
            <span id="isDelete">
              <Translate contentKey="backendHeThongNhungApp.trip.isDelete">Is Delete</Translate>
            </span>
          </dt>
          <dd>{tripEntity.isDelete ? 'true' : 'false'}</dd>
          <dt>
            <Translate contentKey="backendHeThongNhungApp.trip.driver">Driver</Translate>
          </dt>
          <dd>{tripEntity.driver ? tripEntity.driver.id : ''}</dd>
          <dt>
            <Translate contentKey="backendHeThongNhungApp.trip.vehicle">Vehicle</Translate>
          </dt>
          <dd>{tripEntity.vehicle ? tripEntity.vehicle.id : ''}</dd>
        </dl>
        <Button tag={Link} to="/trip" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/trip/${tripEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default TripDetail;

// CodeMADD/src/main/webapp/app/entities/trip/detail/trip-detail.component.ts
import { Component, Input } from '@angular/core';
import { ActivatedRoute, RouterModule } from '@angular/router';

import SharedModule from 'app/shared/shared.module';
import { DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe } from 'app/shared/date';
import { ITrip } from '../trip.model';

@Component({
  standalone: true,
  selector: 'jhi-trip-detail',
  templateUrl: './trip-detail.component.html',
  imports: [SharedModule, RouterModule, DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe],
})
export class TripDetailComponent {
  @Input() trip: ITrip | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <div *ngIf="trip">
      <h2 data-cy="tripDetailsHeading">
        <span jhiTranslate="codeMaddApp.trip.detail.title">__jhiTransformTranslate__('codeMaddApp.trip.detail.title')</span>
      </h2>

      <hr />

      <jhi-alert-error></jhi-alert-error>

      <jhi-alert></jhi-alert>

      <dl class="row-md jh-entity-details">
        <dt><span jhiTranslate="global.field.id">__jhiTransformTranslate__('global.field.id')</span></dt>
        <dd>
          <span>{{ trip.id }}</span>
        </dd>
        <dt><span jhiTranslate="codeMaddApp.trip.startTime">__jhiTransformTranslate__('codeMaddApp.trip.startTime')</span></dt>
        <dd>
          <span>{{ trip.startTime | formatMediumDatetime }}</span>
        </dd>
        <dt><span jhiTranslate="codeMaddApp.trip.endTime">__jhiTransformTranslate__('codeMaddApp.trip.endTime')</span></dt>
        <dd>
          <span>{{ trip.endTime | formatMediumDatetime }}</span>
        </dd>
        <dt><span jhiTranslate="codeMaddApp.trip.status">__jhiTransformTranslate__('codeMaddApp.trip.status')</span></dt>
        <dd>
          <span jhiTranslate="{{ 'codeMaddApp.TripStatus.' + trip.status }}">{{ trip.status }}</span>
        </dd>
        <dt><span jhiTranslate="codeMaddApp.trip.driver">__jhiTransformTranslate__('codeMaddApp.trip.driver')</span></dt>
        <dd>
          <div *ngIf="trip.driver">
            <a [routerLink]="['/driver', trip.driver.id, 'view']">{{ trip.driver.id }}</a>
          </div>
        </dd>
        <dt><span jhiTranslate="codeMaddApp.trip.vehicle">__jhiTransformTranslate__('codeMaddApp.trip.vehicle')</span></dt>
        <dd>
          <div *ngIf="trip.vehicle">
            <a [routerLink]="['/vehicle', trip.vehicle.id, 'view']">{{ trip.vehicle.id }}</a>
          </div>
        </dd>
      </dl>

      <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
        <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back"
          >__jhiTransformTranslate__('entity.action.back')</span
        >
      </button>

      <button type="button" [routerLink]="['/trip', trip.id, 'edit']" class="btn btn-primary">
        <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit"
          >__jhiTransformTranslate__('entity.action.edit')</span
        >
      </button>
    </div>
  </div>
</div>
