// CodeMADD/src/main/webapp/app/entities/violation/detail/violation-detail.component.ts
import { Component, Input } from '@angular/core';
import { ActivatedRoute, RouterModule } from '@angular/router';

import SharedModule from 'app/shared/shared.module';
import { DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe } from 'app/shared/date';
import { IViolation } from '../violation.model';

@Component({
  standalone: true,
  selector: 'jhi-violation-detail',
  templateUrl: './violation-detail.component.html',
  imports: [SharedModule, RouterModule, DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe],
})
export class ViolationDetailComponent {
  @Input() violation: IViolation | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <div *ngIf="violation">
      <h2 data-cy="violationDetailsHeading">
        <span jhiTranslate="codeMaddApp.violation.detail.title">__jhiTransformTranslate__('codeMaddApp.violation.detail.title')</span>
      </h2>

      <hr />

      <jhi-alert-error></jhi-alert-error>

      <jhi-alert></jhi-alert>

      <dl class="row-md jh-entity-details">
        <dt><span jhiTranslate="global.field.id">__jhiTransformTranslate__('global.field.id')</span></dt>
        <dd>
          <span>{{ violation.id }}</span>
        </dd>
        <dt><span jhiTranslate="codeMaddApp.violation.type">__jhiTransformTranslate__('codeMaddApp.violation.type')</span></dt>
        <dd>
          <span jhiTranslate="{{ 'codeMaddApp.ViolationType.' + violation.type }}">{{ violation.type }}</span>
        </dd>
        <dt><span jhiTranslate="codeMaddApp.violation.value">__jhiTransformTranslate__('codeMaddApp.violation.value')</span></dt>
        <dd>
          <span>{{ violation.value }}</span>
        </dd>
        <dt><span jhiTranslate="codeMaddApp.violation.timestamp">__jhiTransformTranslate__('codeMaddApp.violation.timestamp')</span></dt>
        <dd>
          <span>{{ violation.timestamp | formatMediumDatetime }}</span>
        </dd>
        <dt><span jhiTranslate="codeMaddApp.violation.trip">__jhiTransformTranslate__('codeMaddApp.violation.trip')</span></dt>
        <dd>
          <div *ngIf="violation.trip">
            <a [routerLink]="['/trip', violation.trip.id, 'view']">{{ violation.trip.id }}</a>
          </div>
        </dd>
      </dl>

      <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
        <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back"
          >__jhiTransformTranslate__('entity.action.back')</span
        >
      </button>

      <button type="button" [routerLink]="['/violation', violation.id, 'edit']" class="btn btn-primary">
        <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit"
          >__jhiTransformTranslate__('entity.action.edit')</span
        >
      </button>
    </div>
  </div>
</div>

// BackendHeThongNhung/src/main/webapp/app/entities/violation/violation-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './violation.reducer';

export const ViolationDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const violationEntity = useAppSelector(state => state.violation.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="violationDetailsHeading">
          <Translate contentKey="backendHeThongNhungApp.violation.detail.title">Violation</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{violationEntity.id}</dd>
          <dt>
            <span id="value">
              <Translate contentKey="backendHeThongNhungApp.violation.value">Value</Translate>
            </span>
          </dt>
          <dd>{violationEntity.value}</dd>
          <dt>
            <span id="timestamp">
              <Translate contentKey="backendHeThongNhungApp.violation.timestamp">Timestamp</Translate>
            </span>
          </dt>
          <dd>
            {violationEntity.timestamp ? <TextFormat value={violationEntity.timestamp} type="date" format={APP_DATE_FORMAT} /> : null}
          </dd>
          <dt>
            <span id="type">
              <Translate contentKey="backendHeThongNhungApp.violation.type">Type</Translate>
            </span>
          </dt>
          <dd>{violationEntity.type}</dd>
          <dt>
            <Translate contentKey="backendHeThongNhungApp.violation.trip">Trip</Translate>
          </dt>
          <dd>{violationEntity.trip ? violationEntity.trip.id : ''}</dd>
        </dl>
        <Button tag={Link} to="/violation" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/violation/${violationEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default ViolationDetail;
