// src/main/webapp/app/entities/driver/driver-update.tsx
import React, { useState, useEffect } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Button, Row, Col, FormText } from 'reactstrap';
import { isNumber, Translate, translate, ValidatedField, ValidatedForm } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { IDriver } from 'app/shared/model/driver.model';
import { DriverStatus } from 'app/shared/model/enumerations/driver-status.model';
import { getEntity, updateEntity, createEntity, reset } from './driver.reducer';

export const DriverUpdate = () => {
  const dispatch = useAppDispatch();

  const navigate = useNavigate();

  const { id } = useParams<'id'>();
  const isNew = id === undefined;

  const driverEntity = useAppSelector(state => state.driver.entity);
  const loading = useAppSelector(state => state.driver.loading);
  const updating = useAppSelector(state => state.driver.updating);
  const updateSuccess = useAppSelector(state => state.driver.updateSuccess);
  const driverStatusValues = Object.keys(DriverStatus);

  const handleClose = () => {
    navigate('/driver' + location.search);
  };

  useEffect(() => {
    if (isNew) {
      dispatch(reset());
    } else {
      dispatch(getEntity(id));
    }
  }, []);

  useEffect(() => {
    if (updateSuccess) {
      handleClose();
    }
  }, [updateSuccess]);

  const saveEntity = values => {
    values.createdAt = convertDateTimeToServer(values.createdAt);

    const entity = {
      ...driverEntity,
      ...values,
    };

    if (isNew) {
      dispatch(createEntity(entity));
    } else {
      dispatch(updateEntity(entity));
    }
  };

  const defaultValues = () =>
    isNew
      ? {
          createdAt: displayDefaultDateTime(),
        }
      : {
          status: 'ACTIVE',
          ...driverEntity,
          createdAt: convertDateTimeFromServer(driverEntity.createdAt),
        };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="backendHeThongNhungApp.driver.home.createOrEditLabel" data-cy="DriverCreateUpdateHeading">
            <Translate contentKey="backendHeThongNhungApp.driver.home.createOrEditLabel">Create or edit a Driver</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <ValidatedForm defaultValues={defaultValues()} onSubmit={saveEntity}>
              {!isNew ? (
                <ValidatedField
                  name="id"
                  required
                  readOnly
                  id="driver-id"
                  label={translate('global.field.id')}
                  validate={{ required: true }}
                />
              ) : null}
              <ValidatedField
                label="Name"
                id="driver-name"
                name="name"
                data-cy="name"
                type="text"
                validate={{
                  required: { value: true, message: translate('entity.validation.required') },
                }}
              />
              <ValidatedField label="Rfid Uid" id="driver-rfidUid" name="rfidUid" data-cy="rfidUid" type="text" />
              <ValidatedField label="License Number" id="driver-licenseNumber" name="licenseNumber" data-cy="licenseNumber" type="text" />
              <ValidatedField label="Face Data" id="driver-faceData" name="faceData" data-cy="faceData" type="textarea" />
              <ValidatedField
                label="Created At"
                id="driver-createdAt"
                name="createdAt"
                data-cy="createdAt"
                type="datetime-local"
                placeholder="YYYY-MM-DD HH:mm"
              />
              <ValidatedField label="Status" id="driver-status" name="status" data-cy="status" type="select">
                {driverStatusValues.map(driverStatus => (
                  <option value={driverStatus} key={driverStatus}>
                    {driverStatus}
                  </option>
                ))}
              </ValidatedField>
              <Button tag={Link} id="cancel-save" data-cy="entityCreateCancelButton" to="/driver" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </ValidatedForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

export default DriverUpdate;

// CodeMADD/src/main/webapp/app/entities/driver/update/driver-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize } from 'rxjs/operators';

import SharedModule from 'app/shared/shared.module';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';

import { AlertError } from 'app/shared/alert/alert-error.model';
import { EventManager, EventWithContent } from 'app/core/util/event-manager.service';
import { DataUtils, FileLoadError } from 'app/core/util/data-util.service';
import { DriverStatus } from 'app/entities/enumerations/driver-status.model';
import { DriverService } from '../service/driver.service';
import { IDriver } from '../driver.model';
import { DriverFormService, DriverFormGroup } from './driver-form.service';

@Component({
  standalone: true,
  selector: 'jhi-driver-update',
  templateUrl: './driver-update.component.html',
  imports: [SharedModule, FormsModule, ReactiveFormsModule],
})
export class DriverUpdateComponent implements OnInit {
  isSaving = false;
  driver: IDriver | null = null;
  driverStatusValues = Object.keys(DriverStatus);

  editForm: DriverFormGroup = this.driverFormService.createDriverFormGroup();

  constructor(
    protected dataUtils: DataUtils,
    protected eventManager: EventManager,
    protected driverService: DriverService,
    protected driverFormService: DriverFormService,
    protected activatedRoute: ActivatedRoute,
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ driver }) => {
      this.driver = driver;
      if (driver) {
        this.updateForm(driver);
      }
    });
  }

  byteSize(base64String: string): string {
    return this.dataUtils.byteSize(base64String);
  }

  openFile(base64String: string, contentType: string | null | undefined): void {
    this.dataUtils.openFile(base64String, contentType);
  }

  setFileData(event: Event, field: string, isImage: boolean): void {
    this.dataUtils.loadFileToForm(event, this.editForm, field, isImage).subscribe({
      error: (err: FileLoadError) =>
        this.eventManager.broadcast(new EventWithContent<AlertError>('codeMaddApp.error', { message: err.message })),
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const driver = this.driverFormService.getDriver(this.editForm);
    if (driver.id !== null) {
      this.subscribeToSaveResponse(this.driverService.update(driver));
    } else {
      this.subscribeToSaveResponse(this.driverService.create(driver));
    }
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IDriver>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe({
      next: () => this.onSaveSuccess(),
      error: () => this.onSaveError(),
    });
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(driver: IDriver): void {
    this.driver = driver;
    this.driverFormService.resetForm(this.editForm, driver);
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2 id="jhi-driver-heading" data-cy="DriverCreateUpdateHeading" jhiTranslate="codeMaddApp.driver.home.createOrEditLabel">
        __jhiTransformTranslate__('codeMaddApp.driver.home.createOrEditLabel')
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="mb-3" *ngIf="editForm.controls.id.value !== null">
          <label class="form-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="mb-3">
          <label class="form-label" jhiTranslate="codeMaddApp.driver.name" for="field_name">Name</label>
          <input type="text" class="form-control" name="name" id="field_name" data-cy="name" formControlName="name" />
          <div *ngIf="editForm.get('name')!.invalid && (editForm.get('name')!.dirty || editForm.get('name')!.touched)">
            <small class="form-text text-danger" *ngIf="editForm.get('name')?.errors?.required" jhiTranslate="entity.validation.required"
              >__jhiTransformTranslate__('entity.validation.required')</small
            >
          </div>
        </div>

        <div class="mb-3">
          <label class="form-label" jhiTranslate="codeMaddApp.driver.rfidUid" for="field_rfidUid">Rfid Uid</label>
          <input type="text" class="form-control" name="rfidUid" id="field_rfidUid" data-cy="rfidUid" formControlName="rfidUid" />
          <div *ngIf="editForm.get('rfidUid')!.invalid && (editForm.get('rfidUid')!.dirty || editForm.get('rfidUid')!.touched)">
            <small class="form-text text-danger" *ngIf="editForm.get('rfidUid')?.errors?.required" jhiTranslate="entity.validation.required"
              >__jhiTransformTranslate__('entity.validation.required')</small
            >
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('rfidUid')?.errors?.maxlength"
              jhiTranslate="entity.validation.maxlength"
              [translateValues]="{ max: 20 }"
              >__jhiTransformTranslate__('entity.validation.maxlength', { "max": 20 })</small
            >
          </div>
        </div>

        <div class="mb-3">
          <label class="form-label" jhiTranslate="codeMaddApp.driver.licenseNumber" for="field_licenseNumber">License Number</label>
          <input
            type="text"
            class="form-control"
            name="licenseNumber"
            id="field_licenseNumber"
            data-cy="licenseNumber"
            formControlName="licenseNumber"
          />
          <div
            *ngIf="
              editForm.get('licenseNumber')!.invalid && (editForm.get('licenseNumber')!.dirty || editForm.get('licenseNumber')!.touched)
            "
          >
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('licenseNumber')?.errors?.required"
              jhiTranslate="entity.validation.required"
              >__jhiTransformTranslate__('entity.validation.required')</small
            >
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('licenseNumber')?.errors?.maxlength"
              jhiTranslate="entity.validation.maxlength"
              [translateValues]="{ max: 20 }"
              >__jhiTransformTranslate__('entity.validation.maxlength', { "max": 20 })</small
            >
          </div>
        </div>

        <div class="mb-3">
          <label class="form-label" jhiTranslate="codeMaddApp.driver.faceData" for="field_faceData">Face Data</label>
          <textarea class="form-control" name="faceData" id="field_faceData" data-cy="faceData" formControlName="faceData"></textarea>
        </div>

        <div class="mb-3">
          <label class="form-label" jhiTranslate="codeMaddApp.driver.createdAt" for="field_createdAt">Created At</label>
          <div class="d-flex">
            <input
              id="field_createdAt"
              data-cy="createdAt"
              type="datetime-local"
              class="form-control"
              name="createdAt"
              formControlName="createdAt"
              placeholder="YYYY-MM-DD HH:mm"
            />
          </div>
        </div>

        <div class="mb-3">
          <label class="form-label" jhiTranslate="codeMaddApp.driver.status" for="field_status">Status</label>
          <select class="form-control" name="status" formControlName="status" id="field_status" data-cy="status">
            <option [ngValue]="null"></option>
            <option *ngFor="let driverStatus of driverStatusValues" [value]="driverStatus">{{ driverStatus }}</option>
          </select>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" data-cy="entityCreateCancelButton" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel"
            >__jhiTransformTranslate__('entity.action.cancel')</span
          >
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save"
            >__jhiTransformTranslate__('entity.action.save')</span
          >
        </button>
      </div>
    </form>
  </div>
</div>
