// CodeMADD/src/main/webapp/app/entities/driver/detail/driver-detail.component.ts
import { Component, Input } from '@angular/core';
import { ActivatedRoute, RouterModule } from '@angular/router';

import SharedModule from 'app/shared/shared.module';
import { DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe } from 'app/shared/date';
import { DataUtils } from 'app/core/util/data-util.service';
import { IDriver } from '../driver.model';

@Component({
  standalone: true,
  selector: 'jhi-driver-detail',
  templateUrl: './driver-detail.component.html',
  imports: [SharedModule, RouterModule, DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe],
})
export class DriverDetailComponent {
  @Input() driver: IDriver | null = null;

  constructor(
    protected dataUtils: DataUtils,
    protected activatedRoute: ActivatedRoute,
  ) {}

  byteSize(base64String: string): string {
    return this.dataUtils.byteSize(base64String);
  }

  openFile(base64String: string, contentType: string | null | undefined): void {
    this.dataUtils.openFile(base64String, contentType);
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <div *ngIf="driver">
      <h2 data-cy="driverDetailsHeading">
        <span jhiTranslate="codeMaddApp.driver.detail.title">__jhiTransformTranslate__('codeMaddApp.driver.detail.title')</span>
      </h2>

      <hr />

      <jhi-alert-error></jhi-alert-error>

      <jhi-alert></jhi-alert>

      <dl class="row-md jh-entity-details">
        <dt><span jhiTranslate="global.field.id">__jhiTransformTranslate__('global.field.id')</span></dt>
        <dd>
          <span>{{ driver.id }}</span>
        </dd>
        <dt><span jhiTranslate="codeMaddApp.driver.name">__jhiTransformTranslate__('codeMaddApp.driver.name')</span></dt>
        <dd>
          <span>{{ driver.name }}</span>
        </dd>
        <dt><span jhiTranslate="codeMaddApp.driver.rfidUid">__jhiTransformTranslate__('codeMaddApp.driver.rfidUid')</span></dt>
        <dd>
          <span>{{ driver.rfidUid }}</span>
        </dd>
        <dt><span jhiTranslate="codeMaddApp.driver.licenseNumber">__jhiTransformTranslate__('codeMaddApp.driver.licenseNumber')</span></dt>
        <dd>
          <span>{{ driver.licenseNumber }}</span>
        </dd>
        <dt><span jhiTranslate="codeMaddApp.driver.faceData">__jhiTransformTranslate__('codeMaddApp.driver.faceData')</span></dt>
        <dd>
          <span>{{ driver.faceData }}</span>
        </dd>
        <dt><span jhiTranslate="codeMaddApp.driver.createdAt">__jhiTransformTranslate__('codeMaddApp.driver.createdAt')</span></dt>
        <dd>
          <span>{{ driver.createdAt | formatMediumDatetime }}</span>
        </dd>
        <dt><span jhiTranslate="codeMaddApp.driver.status">__jhiTransformTranslate__('codeMaddApp.driver.status')</span></dt>
        <dd>
          <span jhiTranslate="{{ 'codeMaddApp.DriverStatus.' + driver.status }}">{{ driver.status }}</span>
        </dd>
      </dl>

      <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
        <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back"
          >__jhiTransformTranslate__('entity.action.back')</span
        >
      </button>

      <button type="button" [routerLink]="['/driver', driver.id, 'edit']" class="btn btn-primary">
        <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit"
          >__jhiTransformTranslate__('entity.action.edit')</span
        >
      </button>
    </div>
  </div>
</div>

// src/main/webapp/app/entities/driver/driver-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate, byteSize, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './driver.reducer';

export const DriverDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const driverEntity = useAppSelector(state => state.driver.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="driverDetailsHeading">
          <Translate contentKey="backendHeThongNhungApp.driver.detail.title">Driver</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{driverEntity.id}</dd>
          <dt>
            <span id="name">
              <Translate contentKey="backendHeThongNhungApp.driver.name">Name</Translate>
            </span>
          </dt>
          <dd>{driverEntity.name}</dd>
          <dt>
            <span id="rfidUid">
              <Translate contentKey="backendHeThongNhungApp.driver.rfidUid">Rfid Uid</Translate>
            </span>
          </dt>
          <dd>{driverEntity.rfidUid}</dd>
          <dt>
            <span id="licenseNumber">
              <Translate contentKey="backendHeThongNhungApp.driver.licenseNumber">License Number</Translate>
            </span>
          </dt>
          <dd>{driverEntity.licenseNumber}</dd>
          <dt>
            <span id="faceData">
              <Translate contentKey="backendHeThongNhungApp.driver.faceData">Face Data</Translate>
            </span>
          </dt>
          <dd>{driverEntity.faceData}</dd>
          <dt>
            <span id="createdAt">
              <Translate contentKey="backendHeThongNhungApp.driver.createdAt">Created At</Translate>
            </span>
          </dt>
          <dd>{driverEntity.createdAt ? <TextFormat value={driverEntity.createdAt} type="date" format={APP_DATE_FORMAT} /> : null}</dd>
          <dt>
            <span id="status">
              <Translate contentKey="backendHeThongNhungApp.driver.status">Status</Translate>
            </span>
          </dt>
          <dd>{driverEntity.status}</dd>
        </dl>
        <Button tag={Link} to="/driver" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/driver/${driverEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default DriverDetail;
