// CodeMADD/src/main/webapp/app/entities/trip/update/trip-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize, map } from 'rxjs/operators';

import SharedModule from 'app/shared/shared.module';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';

import { IDriver } from 'app/entities/driver/driver.model';
import { DriverService } from 'app/entities/driver/service/driver.service';
import { IVehicle } from 'app/entities/vehicle/vehicle.model';
import { VehicleService } from 'app/entities/vehicle/service/vehicle.service';
import { TripStatus } from 'app/entities/enumerations/trip-status.model';
import { TripService } from '../service/trip.service';
import { ITrip } from '../trip.model';
import { TripFormService, TripFormGroup } from './trip-form.service';

@Component({
  standalone: true,
  selector: 'jhi-trip-update',
  templateUrl: './trip-update.component.html',
  imports: [SharedModule, FormsModule, ReactiveFormsModule],
})
export class TripUpdateComponent implements OnInit {
  isSaving = false;
  trip: ITrip | null = null;
  tripStatusValues = Object.keys(TripStatus);

  driversSharedCollection: IDriver[] = [];
  vehiclesSharedCollection: IVehicle[] = [];

  editForm: TripFormGroup = this.tripFormService.createTripFormGroup();

  constructor(
    protected tripService: TripService,
    protected tripFormService: TripFormService,
    protected driverService: DriverService,
    protected vehicleService: VehicleService,
    protected activatedRoute: ActivatedRoute,
  ) {}

  compareDriver = (o1: IDriver | null, o2: IDriver | null): boolean => this.driverService.compareDriver(o1, o2);

  compareVehicle = (o1: IVehicle | null, o2: IVehicle | null): boolean => this.vehicleService.compareVehicle(o1, o2);

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ trip }) => {
      this.trip = trip;
      if (trip) {
        this.updateForm(trip);
      }

      this.loadRelationshipsOptions();
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const trip = this.tripFormService.getTrip(this.editForm);
    if (trip.id !== null) {
      this.subscribeToSaveResponse(this.tripService.update(trip));
    } else {
      this.subscribeToSaveResponse(this.tripService.create(trip));
    }
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<ITrip>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe({
      next: () => this.onSaveSuccess(),
      error: () => this.onSaveError(),
    });
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(trip: ITrip): void {
    this.trip = trip;
    this.tripFormService.resetForm(this.editForm, trip);

    this.driversSharedCollection = this.driverService.addDriverToCollectionIfMissing<IDriver>(this.driversSharedCollection, trip.driver);
    this.vehiclesSharedCollection = this.vehicleService.addVehicleToCollectionIfMissing<IVehicle>(
      this.vehiclesSharedCollection,
      trip.vehicle,
    );
  }

  protected loadRelationshipsOptions(): void {
    this.driverService
      .query()
      .pipe(map((res: HttpResponse<IDriver[]>) => res.body ?? []))
      .pipe(map((drivers: IDriver[]) => this.driverService.addDriverToCollectionIfMissing<IDriver>(drivers, this.trip?.driver)))
      .subscribe((drivers: IDriver[]) => (this.driversSharedCollection = drivers));

    this.vehicleService
      .query()
      .pipe(map((res: HttpResponse<IVehicle[]>) => res.body ?? []))
      .pipe(map((vehicles: IVehicle[]) => this.vehicleService.addVehicleToCollectionIfMissing<IVehicle>(vehicles, this.trip?.vehicle)))
      .subscribe((vehicles: IVehicle[]) => (this.vehiclesSharedCollection = vehicles));
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2 id="jhi-trip-heading" data-cy="TripCreateUpdateHeading" jhiTranslate="codeMaddApp.trip.home.createOrEditLabel">
        __jhiTransformTranslate__('codeMaddApp.trip.home.createOrEditLabel')
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="mb-3" *ngIf="editForm.controls.id.value !== null">
          <label class="form-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="mb-3">
          <label class="form-label" jhiTranslate="codeMaddApp.trip.startTime" for="field_startTime">Start Time</label>
          <div class="d-flex">
            <input
              id="field_startTime"
              data-cy="startTime"
              type="datetime-local"
              class="form-control"
              name="startTime"
              formControlName="startTime"
              placeholder="YYYY-MM-DD HH:mm"
            />
          </div>
        </div>

        <div class="mb-3">
          <label class="form-label" jhiTranslate="codeMaddApp.trip.endTime" for="field_endTime">End Time</label>
          <div class="d-flex">
            <input
              id="field_endTime"
              data-cy="endTime"
              type="datetime-local"
              class="form-control"
              name="endTime"
              formControlName="endTime"
              placeholder="YYYY-MM-DD HH:mm"
            />
          </div>
        </div>

        <div class="mb-3">
          <label class="form-label" jhiTranslate="codeMaddApp.trip.status" for="field_status">Status</label>
          <select class="form-control" name="status" formControlName="status" id="field_status" data-cy="status">
            <option [ngValue]="null"></option>
            <option *ngFor="let tripStatus of tripStatusValues" [value]="tripStatus">{{ tripStatus }}</option>
          </select>
        </div>

        <div class="mb-3">
          <label class="form-label" jhiTranslate="codeMaddApp.trip.driver" for="field_driver"
            >__jhiTransformTranslate__('codeMaddApp.trip.driver')</label
          >
          <select
            class="form-control"
            id="field_driver"
            data-cy="driver"
            name="driver"
            formControlName="driver"
            [compareWith]="compareDriver"
          >
            <option [ngValue]="null"></option>
            <option [ngValue]="driverOption" *ngFor="let driverOption of driversSharedCollection">{{ driverOption.id }}</option>
          </select>
        </div>

        <div class="mb-3">
          <label class="form-label" jhiTranslate="codeMaddApp.trip.vehicle" for="field_vehicle"
            >__jhiTransformTranslate__('codeMaddApp.trip.vehicle')</label
          >
          <select
            class="form-control"
            id="field_vehicle"
            data-cy="vehicle"
            name="vehicle"
            formControlName="vehicle"
            [compareWith]="compareVehicle"
          >
            <option [ngValue]="null"></option>
            <option [ngValue]="vehicleOption" *ngFor="let vehicleOption of vehiclesSharedCollection">{{ vehicleOption.id }}</option>
          </select>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" data-cy="entityCreateCancelButton" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel"
            >__jhiTransformTranslate__('entity.action.cancel')</span
          >
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save"
            >__jhiTransformTranslate__('entity.action.save')</span
          >
        </button>
      </div>
    </form>
  </div>
</div>

// src/main/webapp/app/entities/trip/trip-update.tsx
import React, { useState, useEffect } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Button, Row, Col, FormText } from 'reactstrap';
import { isNumber, Translate, translate, ValidatedField, ValidatedForm } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { IDriver } from 'app/shared/model/driver.model';
import { getEntities as getDrivers } from 'app/entities/driver/driver.reducer';
import { IVehicle } from 'app/shared/model/vehicle.model';
import { getEntities as getVehicles } from 'app/entities/vehicle/vehicle.reducer';
import { ITrip } from 'app/shared/model/trip.model';
import { TripStatus } from 'app/shared/model/enumerations/trip-status.model';
import { getEntity, updateEntity, createEntity, reset } from './trip.reducer';

export const TripUpdate = () => {
  const dispatch = useAppDispatch();

  const navigate = useNavigate();

  const { id } = useParams<'id'>();
  const isNew = id === undefined;

  const drivers = useAppSelector(state => state.driver.entities);
  const vehicles = useAppSelector(state => state.vehicle.entities);
  const tripEntity = useAppSelector(state => state.trip.entity);
  const loading = useAppSelector(state => state.trip.loading);
  const updating = useAppSelector(state => state.trip.updating);
  const updateSuccess = useAppSelector(state => state.trip.updateSuccess);
  const tripStatusValues = Object.keys(TripStatus);

  const handleClose = () => {
    navigate('/trip' + location.search);
  };

  useEffect(() => {
    if (isNew) {
      dispatch(reset());
    } else {
      dispatch(getEntity(id));
    }

    dispatch(getDrivers({}));
    dispatch(getVehicles({}));
  }, []);

  useEffect(() => {
    if (updateSuccess) {
      handleClose();
    }
  }, [updateSuccess]);

  const saveEntity = values => {
    values.startTime = convertDateTimeToServer(values.startTime);
    values.endTime = convertDateTimeToServer(values.endTime);

    const entity = {
      ...tripEntity,
      ...values,
      driver: drivers.find(it => it.id.toString() === values.driver.toString()),
      vehicle: vehicles.find(it => it.id.toString() === values.vehicle.toString()),
    };

    if (isNew) {
      dispatch(createEntity(entity));
    } else {
      dispatch(updateEntity(entity));
    }
  };

  const defaultValues = () =>
    isNew
      ? {
          startTime: displayDefaultDateTime(),
          endTime: displayDefaultDateTime(),
        }
      : {
          status: 'ONGOING',
          ...tripEntity,
          startTime: convertDateTimeFromServer(tripEntity.startTime),
          endTime: convertDateTimeFromServer(tripEntity.endTime),
          driver: tripEntity?.driver?.id,
          vehicle: tripEntity?.vehicle?.id,
        };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="backendHeThongNhungApp.trip.home.createOrEditLabel" data-cy="TripCreateUpdateHeading">
            <Translate contentKey="backendHeThongNhungApp.trip.home.createOrEditLabel">Create or edit a Trip</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <ValidatedForm defaultValues={defaultValues()} onSubmit={saveEntity}>
              {!isNew ? (
                <ValidatedField
                  name="id"
                  required
                  readOnly
                  id="trip-id"
                  label={translate('global.field.id')}
                  validate={{ required: true }}
                />
              ) : null}
              <ValidatedField
                label="Start Time"
                id="trip-startTime"
                name="startTime"
                data-cy="startTime"
                type="datetime-local"
                placeholder="YYYY-MM-DD HH:mm"
              />
              <ValidatedField
                label="End Time"
                id="trip-endTime"
                name="endTime"
                data-cy="endTime"
                type="datetime-local"
                placeholder="YYYY-MM-DD HH:mm"
              />
              <ValidatedField label="Status" id="trip-status" name="status" data-cy="status" type="select">
                {tripStatusValues.map(tripStatus => (
                  <option value={tripStatus} key={tripStatus}>
                    {tripStatus}
                  </option>
                ))}
              </ValidatedField>
              <ValidatedField id="trip-driver" name="driver" data-cy="driver" label="Driver" type="select">
                <option value="" key="0" />
                {drivers
                  ? drivers.map(otherEntity => (
                      <option value={otherEntity.id} key={otherEntity.id}>
                        {otherEntity.id}
                      </option>
                    ))
                  : null}
              </ValidatedField>
              <ValidatedField id="trip-vehicle" name="vehicle" data-cy="vehicle" label="Vehicle" type="select">
                <option value="" key="0" />
                {vehicles
                  ? vehicles.map(otherEntity => (
                      <option value={otherEntity.id} key={otherEntity.id}>
                        {otherEntity.id}
                      </option>
                    ))
                  : null}
              </ValidatedField>
              <Button tag={Link} id="cancel-save" data-cy="entityCreateCancelButton" to="/trip" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </ValidatedForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

export default TripUpdate;
