// CodeHTN/src/main/webapp/app/entities/vehicle/detail/vehicle-detail.component.ts
import { Component, Input } from '@angular/core';
import { ActivatedRoute, RouterModule } from '@angular/router';

import SharedModule from 'app/shared/shared.module';
import { DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe } from 'app/shared/date';
import { IVehicle } from '../vehicle.model';

@Component({
  standalone: true,
  selector: 'jhi-vehicle-detail',
  templateUrl: './vehicle-detail.component.html',
  imports: [SharedModule, RouterModule, DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe],
})
export class VehicleDetailComponent {
  @Input() vehicle: IVehicle | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <div *ngIf="vehicle">
      <h2 data-cy="vehicleDetailsHeading">
        <span jhiTranslate="codeHtnApp.vehicle.detail.title">__jhiTransformTranslate__('codeHtnApp.vehicle.detail.title')</span>
      </h2>

      <hr />

      <jhi-alert-error></jhi-alert-error>

      <jhi-alert></jhi-alert>

      <dl class="row-md jh-entity-details">
        <dt><span jhiTranslate="global.field.id">__jhiTransformTranslate__('global.field.id')</span></dt>
        <dd>
          <span>{{ vehicle.id }}</span>
        </dd>
        <dt><span jhiTranslate="codeHtnApp.vehicle.licensePlate">__jhiTransformTranslate__('codeHtnApp.vehicle.licensePlate')</span></dt>
        <dd>
          <span>{{ vehicle.licensePlate }}</span>
        </dd>
        <dt><span jhiTranslate="codeHtnApp.vehicle.model">__jhiTransformTranslate__('codeHtnApp.vehicle.model')</span></dt>
        <dd>
          <span>{{ vehicle.model }}</span>
        </dd>
        <dt><span jhiTranslate="codeHtnApp.vehicle.status">__jhiTransformTranslate__('codeHtnApp.vehicle.status')</span></dt>
        <dd>
          <span jhiTranslate="{{ 'codeHtnApp.VehicleStatus.' + vehicle.status }}">{{ vehicle.status }}</span>
        </dd>
      </dl>

      <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
        <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back"
          >__jhiTransformTranslate__('entity.action.back')</span
        >
      </button>

      <button type="button" [routerLink]="['/vehicle', vehicle.id, 'edit']" class="btn btn-primary">
        <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit"
          >__jhiTransformTranslate__('entity.action.edit')</span
        >
      </button>
    </div>
  </div>
</div>

// src/main/webapp/app/entities/vehicle/vehicle-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './vehicle.reducer';

export const VehicleDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const vehicleEntity = useAppSelector(state => state.vehicle.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="vehicleDetailsHeading">
          <Translate contentKey="backendHeThongNhungApp.vehicle.detail.title">Vehicle</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{vehicleEntity.id}</dd>
          <dt>
            <span id="licensePlate">
              <Translate contentKey="backendHeThongNhungApp.vehicle.licensePlate">License Plate</Translate>
            </span>
          </dt>
          <dd>{vehicleEntity.licensePlate}</dd>
          <dt>
            <span id="model">
              <Translate contentKey="backendHeThongNhungApp.vehicle.model">Model</Translate>
            </span>
          </dt>
          <dd>{vehicleEntity.model}</dd>
          <dt>
            <span id="status">
              <Translate contentKey="backendHeThongNhungApp.vehicle.status">Status</Translate>
            </span>
          </dt>
          <dd>{vehicleEntity.status}</dd>
        </dl>
        <Button tag={Link} to="/vehicle" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/vehicle/${vehicleEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default VehicleDetail;
